@extends(proj.'.index')
@section('dirassa')
	@include(proj.'.inscription')
	@include(proj.'.dirassa_info')
	@include(proj.'.slide_news')
	@include(proj.'.slide_post')
	@include(proj.'.partenaire')
@endsection
@stop